name: symphony
description: "An open source music player that contains the main local and offline features."

publish_to: "none"
homepage: https://softyes.com.br
repository: https://github.com/symphony-mp/symphony_desktop

version: 0.1.0+1

environment:
  sdk: ^3.11.5
  flutter: ^3.41.9

dependencies:
  flutter:
    sdk: flutter

  flutter_modular: ^6.4.1
  symphony_ui:
    git:
      ref: main
      url: https://github.com/symphony-mp/symphony_ui
  symphony_engine:
    git:
      ref: main
      url: https://github.com/symphony-mp/symphony_engine

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  icons_launcher: ^3.0.3
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: false
